language: ruby
rvm:
  - jruby-9.2.11.1
jobs:
  include:
    - os: linux
      dist: xenial
      services: 
        - xvfb
      apt:
        packages:
          - libswt-webkit-gtk-3-jni
    - os: osx
