env:
  global:
    - CC_TEST_REPORTER_ID=490a0fe5dffcf934f1bb17cdfb13b8c1c7b5ff9fdfffa48a205c019be3879886
    - JRUBY_OPTS="--debug"
language: ruby
rvm:
  - jruby-9.2.11.1
jobs:
  include:
    - os: linux
      dist: xenial
      services: 
        - xvfb
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - bundle exec rspec
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - os: osx
